services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disattiva l'autenticazione per test
      - ES_JAVA_OPTS=-Xms2g -Xmx2g # Si imposta un limite alla dimensione dello heap del container (almeno 50%) 
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
  mongodb: 
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  esdata:
  mongodata: