services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"    # API S3 compatibile
      - "9001:9001"    # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redisdata:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DOCS_INDEX=docs
      - PAGES_INDEX=pages
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - elasticsearch
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DOCS_INDEX: docs
      PAGES_INDEX: pages
      MINIO_CLIENT_URL: http://minio:9000
      ES_HOST: http://elasticsearch:9200
      CELERY_BROKER_URL: redis://redis:6379/0
      KEYCLOAK_URL: http://keycloak:8080
      REALM_RELATIVE_PATH: /realms/master
      ALGORITHM: RS256
      BUCKET: van-gogh-docs
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
      - elasticsearch
      - keycloak
    networks:
      - backend

volumes:
  esdata:
  minio_data:
  pgdata:
  redisdata: 

networks:
  backend:
    driver: bridge